import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { EggStorage } from '../src/main/eggStorage'

let root: string, config: string, original: string, destination: string
const create = () => new EggStorage(config, original, [path.dirname(config)])
beforeEach(() => {
  root = fs.mkdtempSync(path.join(os.tmpdir(), 'appgacha-storage-test-'))
  config = path.join(root, 'profile/egg-storage.json')
  original = path.join(root, 'original')
  destination = path.join(root, 'destination')
  fs.mkdirSync(original); fs.mkdirSync(destination)
})
afterEach(() => {
  vi.restoreAllMocks()
  if (path.dirname(root) !== os.tmpdir() || !path.basename(root).startsWith('appgacha-storage-test-')) throw new Error('Unsafe test cleanup')
  fs.rmSync(root, { recursive: true, force: true, maxRetries: 3 })
})
function seed() {
  const capsule = path.join(original, '🍅 专注.gacha')
  fs.mkdirSync(path.join(capsule, 'data'), { recursive: true })
  fs.writeFileSync(path.join(capsule, 'manifest.json'), JSON.stringify({ eggId: 'stable-id', name: 'Focus' }))
  fs.writeFileSync(path.join(capsule, 'app.js'), 'code')
  fs.writeFileSync(path.join(capsule, 'data/egg.db'), 'saved user data')
  fs.writeFileSync(path.join(capsule, 'data/egg.db-wal'), 'committed WAL data')
  return capsule
}
describe('custom egg storage', () => {
  it('treats unreadable configuration as recovery, not a clean new installation', async () => {
    const read = fs.readFileSync
    vi.spyOn(fs, 'readFileSync').mockImplementation((...args: Parameters<typeof fs.readFileSync>) => {
      if (String(args[0]) === config) throw Object.assign(new Error('Access denied'), { code: 'EACCES' })
      return read(...args)
    })
    const store = create()
    expect((await store.initialize()).available).toBe(false)
    expect(store.status().error).toContain('Access denied')
    expect(() => store.assertAvailable()).toThrow()
  })
  it.each(['{broken', 'null', '{"directory":42}', '{"pending":{"directory":"relative","copyExisting":true}}'])('keeps Settings accessible with damaged config: %s', async raw => {
    fs.mkdirSync(path.dirname(config)); fs.writeFileSync(config, raw)
    const store = create()
    expect((await store.initialize()).available).toBe(false)
    expect(() => store.assertAvailable()).toThrow('unavailable')
    expect(fs.readFileSync(config, 'utf8')).toBe(raw)
    expect(() => store.schedule(destination, true)).toThrow('turn off copying')
    const pending = store.schedule(destination, false)
    expect(pending.available).toBe(false)
    expect(fs.readFileSync(pending.configBackup!, 'utf8')).toBe(raw)
    expect(() => store.assertAvailable()).toThrow()
    const restarted = create()
    expect((await restarted.initialize()).available).toBe(true)
    expect(restarted.directory).toBe(destination)
  })
  it('does not fall back if config recovery is cancelled or fails at restart', async () => {
    fs.mkdirSync(path.dirname(config)); fs.writeFileSync(config, '{broken')
    const store = create(); await store.initialize()
    store.schedule(destination, false); store.cancel()
    expect((await create().initialize()).available).toBe(false)
    store.schedule(destination, false); fs.rmdirSync(destination)
    const restarted = create()
    expect((await restarted.initialize()).available).toBe(false)
    expect(() => restarted.assertAvailable()).toThrow()
  })
  it('recovers to the default explicitly even when the displayed candidate is already default', async () => {
    fs.mkdirSync(path.dirname(config)); fs.writeFileSync(config, '{broken')
    const store = create(); await store.initialize()
    expect(store.schedule(original, false).pending?.directory).toBe(original)
    expect((await create().initialize()).available).toBe(true)
  })
  it('does not overwrite malformed configuration if its backup fails', async () => {
    fs.mkdirSync(path.dirname(config)); fs.writeFileSync(config, '{broken')
    const store = create(); await store.initialize()
    vi.spyOn(fs, 'copyFileSync').mockImplementationOnce(() => { throw new Error('Backup denied') })
    expect(() => store.schedule(destination, false)).toThrow('Backup denied')
    expect(fs.readFileSync(config, 'utf8')).toBe('{broken')
    expect(store.status().available).toBe(false)
  })
  it('opens in recovery when the library path is a file, and permits choosing a usable library', async () => {
    fs.mkdirSync(path.dirname(config)); fs.writeFileSync(destination + '.txt', 'not a folder')
    fs.writeFileSync(config, JSON.stringify({ directory: destination + '.txt' }))
    const store = create()
    expect((await store.initialize()).available).toBe(false)
    store.schedule(destination, false)
    expect((await create().initialize()).directory).toBe(destination)
    expect(fs.readFileSync(destination + '.txt', 'utf8')).toBe('not a folder')
  })
  it('blocks an inaccessible library without preventing storage status access', async () => {
    vi.spyOn(fs, 'mkdtempSync').mockImplementationOnce(() => { throw new Error('EACCES') })
    const store = create()
    expect((await store.initialize()).available).toBe(false)
    expect(store.status().error).toContain('EACCES')
    expect(() => store.assertAvailable()).toThrow('EACCES')
  })
  it('does not silently recreate a library removed after startup', async () => {
    const store = create(); await store.initialize(); fs.rmdirSync(original)
    expect(() => store.assertAvailable()).toThrow('unavailable')
    expect(fs.existsSync(original)).toBe(false)
  })
  it('keeps the default and changes nothing without user selection', async () => {
    const store = create()
    expect((await store.initialize()).directory).toBe(original)
    expect(fs.existsSync(config)).toBe(false)
  })
  it('defers the path switch to restart, copies complete capsules and retains originals', async () => {
    const capsule = seed(), store = create()
    fs.mkdirSync(path.join(original, '.mcp-install-unfinished'))
    store.schedule(destination, true)
    expect(store.directory).toBe(original)
    expect(fs.readdirSync(destination)).toEqual([])
    const restarted = create()
    expect((await restarted.initialize()).error).toBeUndefined()
    expect(restarted.directory).toBe(destination)
    expect(restarted.status().pending).toBeUndefined()
    const copied = path.join(destination, path.basename(capsule))
    expect(fs.readFileSync(path.join(copied, 'data/egg.db-wal'), 'utf8')).toBe('committed WAL data')
    expect(fs.readFileSync(path.join(copied, 'data/egg.db'), 'utf8')).toBe('saved user data')
    expect(fs.existsSync(capsule)).toBe(true)
    expect(fs.readdirSync(destination)).toEqual([path.basename(capsule)])
    expect(create().directory).toBe(destination)
  })
  it('switches to an existing library without copying or deleting original capsules', async () => {
    seed()
    fs.mkdirSync(path.join(destination, 'Existing.gacha'))
    create().schedule(destination, false)
    const store = create(); await store.initialize()
    expect(store.directory).toBe(destination)
    expect(fs.readdirSync(destination)).toEqual(['Existing.gacha'])
    expect(fs.readdirSync(original)).toEqual(['🍅 专注.gacha'])
    store.schedule(original, false)
    const reset = create(); await reset.initialize()
    expect(reset.directory).toBe(original)
  })
  it('cancels a pending change without touching either library', () => {
    seed()
    const store = create(); store.schedule(destination, true); store.cancel()
    expect(create().status().pending).toBeUndefined()
    expect(fs.readdirSync(destination)).toEqual([])
  })
  it('rejects unsafe/nested paths and refuses to overwrite a populated target', () => {
    const store = create()
    expect(() => store.schedule(path.parse(root).root, true)).toThrow('root')
    expect(() => store.schedule(root, false)).toThrow('contain')
    const nested = path.join(original, 'nested'); fs.mkdirSync(nested)
    expect(() => store.schedule(nested, false)).toThrow('contain')
    const internal = path.join(root, 'profile/mcp'); fs.mkdirSync(internal, { recursive: true })
    expect(() => store.schedule(internal, false)).toThrow('internal')
    fs.writeFileSync(path.join(destination, 'keep.txt'), 'unrelated')
    expect(() => store.schedule(destination, true)).toThrow('empty')
    expect(fs.readFileSync(path.join(destination, 'keep.txt'), 'utf8')).toBe('unrelated')
  })
  it('rechecks the target at restart and keeps the active directory on failure', async () => {
    seed(); create().schedule(destination, true)
    fs.mkdirSync(path.join(destination, 'New.gacha'))
    const store = create(), status = await store.initialize()
    expect(status.error).toContain('empty')
    expect(store.directory).toBe(original)
    expect(status.pending?.directory).toBe(destination)
    expect(fs.readdirSync(destination)).toEqual(['New.gacha'])
  })
  it('does not silently fall back when the configured disk is missing', async () => {
    create().schedule(destination, false)
    await create().initialize()
    fs.rmdirSync(destination)
    const store = create()
    expect((await store.initialize()).error).toContain('unavailable')
    expect(store.directory).toBe(destination)
  })
  it('keeps source and target intact if a file cannot be copied', async () => {
    seed(); create().schedule(destination, true)
    vi.spyOn(fs.promises, 'copyFile').mockRejectedValueOnce(new Error('ENOSPC'))
    const store = create()
    expect((await store.initialize()).error).toContain('ENOSPC')
    expect(store.directory).toBe(original)
    expect(fs.readdirSync(destination)).toEqual([])
    expect(fs.readdirSync(root).some(name => name.startsWith('.appgacha-eggs-copy-'))).toBe(false)
    expect(fs.readFileSync(path.join(original, '🍅 专注.gacha/data/egg.db'), 'utf8')).toBe('saved user data')
  })
  it('rejects directory junctions pointing to an ancestor of the current library', () => {
    const alias = path.join(root, 'alias')
    fs.symlinkSync(root, alias, process.platform === 'win32' ? 'junction' : 'dir')
    expect(() => create().schedule(alias, false)).toThrow('contain')
  })
  it('refuses linked data instead of silently dropping it from the copied capsule', async () => {
    const capsule = seed()
    const external = path.join(root, 'external'); fs.mkdirSync(external)
    fs.symlinkSync(external, path.join(capsule, 'linked'), process.platform === 'win32' ? 'junction' : 'dir')
    create().schedule(destination, true)
    const store = create()
    expect((await store.initialize()).error).toContain('Linked')
    expect(store.directory).toBe(original)
    expect(fs.readdirSync(destination)).toEqual([])
  })
  it('does not switch libraries when saving the new configuration fails', async () => {
    seed(); create().schedule(destination, true)
    const rename = fs.renameSync
    vi.spyOn(fs, 'renameSync').mockImplementation((from, to) => {
      if (to === config) throw new Error('Settings locked')
      return rename(from, to)
    })
    const store = create()
    expect((await store.initialize()).error).toContain('Settings locked')
    expect(store.directory).toBe(original)
    expect(fs.existsSync(path.join(destination, '🍅 专注.gacha/data/egg.db'))).toBe(true)
    expect(fs.existsSync(path.join(original, '🍅 专注.gacha/data/egg.db'))).toBe(true)
  })
})
