export { McpAuth } from '../src/main/mcp/auth'
export { McpDrafts } from '../src/main/mcp/drafts'
export { McpBridge } from '../src/main/mcp/bridge'
export { EggStorage } from '../src/main/eggStorage'
export { installEggAtomically } from '../src/main/atomicEggInstall'
export { registerCapabilities } from '../src/main/capabilities'
export { validateEgg } from '../src/main/validate'
export { testEgg } from '../src/main/test'
export { verifyFinalArtifact } from '../src/main/finalArtifact'
export { registerEgg, getEgg } from '../src/main/eggs'
export { Client } from '@modelcontextprotocol/sdk/client/index.js'
export { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js'
